### PR TITLE
v1.11.4

### PR DESCRIPTION
**Pull request by ocefpaf**
Needed in https://github.com/conda-forge/cppyy-feedstock/pull/33

### CODE REVIEW

**Comment by ocefpaf** [comment]
@isuruf is this OK? I based it on master and created a new branch.

**Comment by ocefpaf** [comment]
Looks like it is not really needed though.

**Comment by saraedum** [comment]
If we need another build of 1.11.4 somehow, then this looks ok to me.

**Comment by saraedum** [comment]
I think this is not needed anymore.

**Pull request closed without merging**
