### PR TITLE
Downgrade to 1.12.12

### PR DESCRIPTION
**Pull request by saraedum**
but keep building against latest Python versions.

This should not have been upgraded to 1.12.13 since 1.12.13 is expected to pin cppyy-cling 6.28.0 which has not been packaged yet. (The intermediate dependency cppyy-backend had been upgraded incorrectly. This is reverted in https://github.com/conda-forge/cppyy-backend-feedstock/pull/42.)

The pins here are exact (at least upstream does that) so we should only upgrade everything at once (or rather from the dependencies up.)

There's no harm done since nobody pulls in cpycppyy except for cppyy and it has not had its pin changed yet.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed). This is a rebuild of the previous version.
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by saraedum** [comment]
@conda-forge-admin, please rerender.

**Comment by h-vetinari** [comment]
Looks like this needs a py311 build for `cppyy-backend 1.14.10`

**Comment by saraedum** [comment]
Yes, seems the build wasn't ready when this PR was created.

**Comment by wlav** [comment]
Just as an aside, cppyy-backend is independent of python, so the same build can serve all versions.

**Pull request merged**
